name: Set up mdBook
description: Set up mdBook

inputs:
  mdbook-version:
    required: true
    description: "the mdBook version to use (like 0.4.37)"

runs:
  using: composite
  steps:
    - name: Install mdBook
      shell: bash
      env:
        MDBOOK_VERSION: v${{ inputs.mdbook-version }}
      # If you get a "not in gzip format" error, it probably means the
      # mdbook-version doesn't exist, or is not formatted correctly.
      run: |
        url="https://github.com/rust-lang/mdbook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir mdbook
        curl -sSL $url | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
