name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup mdBook
        uses: ./.github/actions/mdbook
        with:
          mdbook-version: 0.4.36

      - name: Build
        run: just build

      - name: Test
        run: just test

      - name: Check for uncommitted changes
        run: git diff --exit-code

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Format
        run: just format-ci
